apiVersion: v1
kind: PersistentVolume
metadata:
  name: chartmuseum-pv
  labels:
    name: chartmuseum-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/chartmuseum # path on the disk of this PV
  nodeAffinity: # nodeAffinity is required when using local volumes.
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lima-rancher-desktop #this is the hostname of the worker node
