apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chartmuseum
spec:
  # https://fluxcd.io/flux/components/helm/helmreleases/
  interval: 5m
  releaseName: ac-chartmuseum
  maxHistory: 10
  chart:
    spec:
      chart: chartmuseum
      version: "3.9.0"
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: infra
      interval: 1m
  values:
    env:
      open:
        STORAGE: local
        DISABLE_API: false
    persistence:
      enabled: true
      path: /mnt/chartmuseum
      existingClaim: chartmuseum-pvc
